using InfraPM.Api.Domain.Entities;
using Microsoft.AspNetCore.Identity;

namespace InfraPM.Api.Infrastructure.Data
{
    public static class DbSeeder
    {
        public static async Task SeedSuperuserAsync(IServiceProvider serviceProvider)
        {
            var userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var roleManager = serviceProvider.GetRequiredService<RoleManager<IdentityRole>>();

            var superuserRole = "Superuser";

            // Ensure Superuser role exists
            if (!await roleManager.RoleExistsAsync(superuserRole))
            {
                await roleManager.CreateAsync(new IdentityRole(superuserRole));
            }

            // Create default superuser if none exists
            var adminUsername = "admin";
            if (await userManager.FindByNameAsync(adminUsername) == null)
            {
                var newAdmin = new ApplicationUser
                {
                    UserName = adminUsername,
                    FullName = "System Administrator",
                    SuperuserNotes = "Auto-generated by system startup seeder.",
                    RequiresPasswordChange = true, // Force them to change the default password immediately
                    EmailConfirmed = true
                };

                // Fetch default password from environment variables
                var defaultPassword = Environment.GetEnvironmentVariable("DEFAULT_SUPERUSER_PASSWORD")
                    ?? throw new InvalidOperationException("Cannot seed Superuser. DEFAULT_SUPERUSER_PASSWORD environment variable is missing.");

                var result = await userManager.CreateAsync(newAdmin, defaultPassword);

                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(newAdmin, superuserRole);
                }
                else
                {
                    // For debugging if password policy fails
                    var errors = string.Join(", ", result.Errors.Select(e => e.Description));
                    Console.WriteLine($"Failed to seed Superuser: {errors}");
                }
            }
        }
    }
}